### ISSUE TITLE
run.sh still referenced even though it no longer exists

### ISSUE THREAD

**Issue by exxa-tech** [Australian-Imaging-Service/ctp-build#4]
@dean-taylor changed run.sh to entrypoint.sh in this commit:
https://github.com/Australian-Imaging-Service/ctp-build/commit/894d345b3cdaf05cc672ee75beb73b77399ac0fd

But didn't update in the ctp.pkr.hcl file therefore this won't build. There are two references in this file that needs to change from run.sh to entrypoint.sh:

    "run.sh"
  "ENTRYPOINT [\"/bin/sh\", \"/tmp/run.sh\"]"

**Comment by fxusyd** [comment]
fixed in another PR#7
